In [1]:
import numpy as np
np.__version__

'1.21.5'

# create an 1d array using array function

In [2]:
a = np.array([1,2,3,4,5])
print(a.dtype)
print(a.shape)

int32
(5,)


# create 1d array using arange function

In [3]:
arr = np.arange(10)
print(arr)
print(arr.dtype)
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


# create 2d array using array

In [4]:
b = np.array([[1,2,3,],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# create 2d array using arange function

In [5]:
c = np.arange(18).reshape(6,3)
print(c)
print(c.dtype)
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
int32
(6, 3)


# create 3d array using array function

In [6]:
d =np.array(
    [
    [[1,2,3],[2,3,4]],
    [[3,4,5],[4,5,6]],
    [[5,6,7],[6,7,8]]
    ]
)
print(d)
print(d.dtype)
print(d.shape)
print(d.size)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]

 [[5 6 7]
  [6 7 8]]]
int32
(3, 2, 3)
18


# create 3d array using arange function

In [7]:
e = np.arange(18).reshape(3,2,3)
print(e)
print(e.dtype)
print(e.shape)
print(e.size)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)
18


# Createing array using zeros

In [8]:
f = np.zeros(50).reshape(5,10)
print(f)
print(f.dtype)
print(f.shape)
print(f.size)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
float64
(5, 10)
50


# Createing array using ones

In [9]:
g = np.ones(10).reshape(2,5)
print(g)
print(g.dtype)
print(g.shape)
print(g.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
(2, 5)
10


# Createing  ones using 2D array

In [10]:
g = np.ones((4,2),dtype=np.int64)
g


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

# Createing ones using 3D array

In [11]:
g =np.ones((3,2,3),dtype=np.int32)
g

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# creating random numbers using 1d array

In [12]:
h = np.random.randint(1,3,size=(10))
print(h)
print(h.dtype)
print(h.shape)

[1 1 1 2 1 1 1 1 2 1]
int32
(10,)


# creating random numbers using 2d array

In [13]:
i =np.random.randint(1,5,size =(5,5))
print(i)
print(i.dtype)
print(i.shape)

[[4 4 1 3 3]
 [3 3 3 2 2]
 [1 2 4 2 4]
 [1 4 3 1 2]
 [1 2 4 4 3]]
int32
(5, 5)


# creating random numbers using 3d array

In [14]:
j =np.random.randint(1,10,size=(3,3,3))
print(j)
print(j.dtype)
print(j.shape)

[[[1 7 9]
  [6 8 8]
  [6 6 6]]

 [[5 8 3]
  [9 9 6]
  [2 1 8]]

 [[1 2 7]
  [6 2 4]
  [6 4 5]]]
int32
(3, 3, 3)


# create array with single low multipal high

In [15]:
k =np.random.randint(5,[10,20,30,40,50])
print(k)
print(k.dtype)
print(k.shape)

[ 9 14 29  9 46]
int32
(5,)


# create array with single high multipal low

In [16]:
l =np.random.randint([10,20,30,40],50)
print(l)
print(l.dtype)
print(l.shape)


[10 41 32 48]
int32
(4,)


# create array with multipal low mulyipal high

In [17]:
m =np.random.randint([1,2,3],[10,20,30])
print(m)
print(m.dtype)
print(m.shape)

[ 5 15 13]
int32
(3,)


# random.randn function 1D

In [18]:
n = np.random.randn(3)
n

array([-0.51477007,  1.88974266, -0.85571306])

# random.randn function 2D

In [19]:
o =np.random.randn(3,3)
print(o)
print(o.dtype)
print(o.shape)
print(o.size)

[[0.43777593 0.42702258 0.43542398]
 [0.39975624 1.0245444  1.49571952]
 [0.70480936 0.06511946 0.17639503]]
float64
(3, 3)
9


# random.randn function 3D

In [20]:
p =np.random.randn(3,3,3)
print(p)
print(p.dtype)
print(p.shape)
print(p.size)

[[[ 0.70413075  0.12739158 -0.74753427]
  [ 2.81189457  0.04042985 -0.75634242]
  [ 0.09652655 -0.15177361  0.3958074 ]]

 [[-1.27664834 -0.70015363  0.81172769]
  [-0.44144647  0.46230307  1.5731002 ]
  [-0.32899607  0.84747789  0.23379065]]

 [[ 1.43316512  1.2428617  -0.94623108]
  [ 0.72710178  0.04465966  0.70307814]
  [ 0.27908136 -0.8300414   0.49176456]]]
float64
(3, 3, 3)
27


# creating rand function

In [21]:
q =np.random.rand(10)
print(q)
print(q.shape)
print(q.dtype)
print(q.size)

[0.66808897 0.61589887 0.21966766 0.81468264 0.63239113 0.55117414
 0.17942134 0.68992942 0.38789919 0.80593336]
(10,)
float64
10


# creating array positive indexing

In [22]:
r =np.array([1,2,3,4])
print(r[3])

4


# creating array positive indexing 2D

In [23]:
r =np.array([[1,2,3,4],[5,6,7,8]])
print(r[1,0])
print(r[0,2])

5
3


# creating array positive indexing 3D

In [24]:
r =np.array(
    [
        [[1,2,3],[2,3,4]],
        [[3,4,5],[4,5,6]],
        [[5,6,7],[6,7,8]]
    ]
)
print(r[0,1,0])
print(r[1,1,2])

2
6


# creating array negative indexing 1D

In [25]:
s =np.array([1,2,3,4,5])
print(s[-2])

4


# creating array negative indexing 2D

In [26]:
s =np.array([[1,2,3,4],[5,6,7,8]])
print(s[-1,-1])
print(s[-2,-3])

8
2


# creating array negative indexing 3D

In [27]:
s =np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
print(s[-1,-1,-3])
print(s[-1,-2,-1])
print(s[-3,-1,-1])

6
7
4


# numpy array slicing

# slice elements from index 1to index 5 from the folling array

In [28]:
        #    0 1 2 3 4 5   
t =np.array([1,2,3,4,5,6])
print(t[1:5])

[2 3 4 5]


# slice elements from index 4to end array


In [29]:
        #    0 1 2 3 4 5 6
t =np.array([1,2,3,4,5,6,7])
print(t[4:7])

[5 6 7]


# slice elements from start to index 4 (not include)

In [30]:
#            0 1 2 3 4
t =np.array([1,2,3,4,5])
print(t[:4])

[1 2 3 4]


# negative slicing

slice from index 3 from end of to index 1 from end


In [31]:
 #           7 6 5 4 3 2 1
u =np.array([1,2,3,4,5,6,7])
print(u[-3:-1])

[5 6]


return every eliments from index 1 to index 5

In [32]:
u =np.array([1,2,3,4,5,6,7])
print(u[-1:-5:-2])

[7 5]


return every outher elements from the entire array

In [33]:
u =np.array([1,2,3,4,5,6,7])
print(u[::3])

[1 4 7]


# slicing 2d array

from second element from index 1 to index 4 (not included)

In [34]:
v =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(v[1,1:4])
print(v[0,0:4])

[7 8 9]
[1 2 3 4]


# from both array return index 2

In [35]:
v =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(v[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Array Copy vs View 

In [36]:
#copy
r =np.array([1,2,3,4,5])
s =np.copy(r)
r[0]=6
s[1]=7
print(r)
print(s)

[6 2 3 4 5]
[1 7 3 4 5]


In [37]:
#view
r =np.array([1,2,3,4,5])
s =r.view()
r[0]=6
print(r)
print(s)

[6 2 3 4 5]
[6 2 3 4 5]


# RESHAPING

In [38]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Original Array")
print(a1)
a2 =a1.reshape(4,3)
print("\nArray dimensions are 4,3")
print(a2)
a3 =a1.reshape(2,3,2)
print("\nArray dimensions are 2,3,2")
print(a3)

Original Array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array dimensions are 4,3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array dimensions are 2,3,2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# SUM FUNCTION

In [39]:
z =np.array([10,20,30,40])
print(z)
print(np.sum(z))

[10 20 30 40]
100


In [40]:
z1=np.array([[1,2,3,4],[2,3,4,5]])
print("Original Array")
print(z1)

print("\n sum axis 0")
print(np.sum(z1,axis=0))

print("\n sum axis 1")
print(np.sum(z1,axis=1))

Original Array
[[1 2 3 4]
 [2 3 4 5]]

 sum axis 0
[3 5 7 9]

 sum axis 1
[10 14]


# MEAN FUNCTION

In [43]:
z1=np.array([[1,2,3,4],[2,3,4,5]])
print("Original Array")
print(np.mean(z1))

print("\n mean axis 0")
print(np.mean(z1,axis=0))

print("\n meanaxis 1")
print(np.mean(z1,axis=1))

Original Array
3.0

 mean axis 0
[1.5 2.5 3.5 4.5]

 meanaxis 1
[2.5 3.5]


# STD FUNCTION

In [44]:
a2 =np.array([[1,2],[3,4]])
print("std org")
print(np.std(a2))
print("\nstd axis 0")
print(np.std(a2,axis=0))
print("\nstd axis 1")
print(np.std(a2,axis=1))

std org
1.118033988749895

std axis 0
[1. 1.]

std axis 1
[0.5 0.5]


# MIN FUNCTION

In [2]:
a2 =np.array([[1,2],[3,4]])
print("min org")
print(np.std(a2))
print("\nmin axis 0")
print(np.min(a2,axis=0))
print("\nmin axis 1")
print(np.min(a2,axis=1))

min org
1.118033988749895

min axis 0
[1 2]

min axis 1
[1 3]


# VAR FUNCTION

In [4]:
a2 =np.array([[1,2],[3,4]])
print("var org")
print(np.var(a2))
print("\nvar axis 0")
print(np.var(a2,axis=0))
print("\nvar axis 1")
print(np.var(a2,axis=1))

var org
1.25

var axis 0
[1. 1.]

var axis 1
[0.25 0.25]


# MAX FUNCTIOM

In [5]:
a2 =np.array([[1,2],[3,4]])
print("max org")
print(np.max(a2))
print("\nmax axis 0")
print(np.max(a2,axis=0))
print("\nmax axis 1")
print(np.max(a2,axis=1))

max org
4

max axis 0
[3 4]

max axis 1
[2 4]
