In [2]:
import numpy as np
np.__version__

'1.21.5'

# create an 1d array using array function

In [2]:
a = np.array([1,2,3,4,5])
print(a.dtype)
print(a.shape)

int32
(5,)


# create 1d array using arange function

In [3]:
arr = np.arange(10)
print(arr)
print(arr.dtype)
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


# create 2d array using array

In [4]:
b = np.array([[1,2,3,],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# create 2d array using arange function

In [5]:
c = np.arange(18).reshape(6,3)
print(c)
print(c.dtype)
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
int32
(6, 3)


# create 3d array using array function

In [6]:
d =np.array(
    [
    [[1,2,3],[2,3,4]],
    [[3,4,5],[4,5,6]],
    [[5,6,7],[6,7,8]]
    ]
)
print(d)
print(d.dtype)
print(d.shape)
print(d.size)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]

 [[5 6 7]
  [6 7 8]]]
int32
(3, 2, 3)
18


# create 3d array using arange function

In [7]:
e = np.arange(18).reshape(3,2,3)
print(e)
print(e.dtype)
print(e.shape)
print(e.size)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)
18


# Createing array using zeros

In [8]:
f = np.zeros(50).reshape(5,10)
print(f)
print(f.dtype)
print(f.shape)
print(f.size)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
float64
(5, 10)
50


# Createing array using ones

In [9]:
g = np.ones(10).reshape(2,5)
print(g)
print(g.dtype)
print(g.shape)
print(g.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
(2, 5)
10


# Createing  ones using 2D array

In [10]:
g = np.ones((4,2),dtype=np.int64)
g


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

# Createing ones using 3D array

In [11]:
g =np.ones((3,2,3),dtype=np.int32)
g

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# creating random numbers using 1d array

In [21]:
h = np.random.randint(1,3,size=(10))
print(h)
print(h.dtype)
print(h.shape)

[1 1 1 1 1 1 1 2 1 2]
int32
(10,)


# creating random numbers using 2d array

In [29]:
i =np.random.randint(1,5,size =(5,5))
print(i)
print(i.dtype)
print(i.shape)

[[1 3 1 3 2]
 [3 3 1 2 2]
 [1 2 3 2 2]
 [2 2 1 4 1]
 [2 2 4 1 4]]
int32
(5, 5)


# creating random numbers using 3d array

In [32]:
j =np.random.randint(1,10,size=(3,3,3))
print(j)
print(j.dtype)
print(j.shape)

[[[3 9 8]
  [7 8 6]
  [3 1 2]]

 [[9 1 1]
  [8 1 9]
  [5 3 1]]

 [[6 8 8]
  [8 8 5]
  [2 7 3]]]
int32
(3, 3, 3)


# create array with single low multipal high

In [44]:
k =np.random.randint(5,[10,20,30,40,50])
print(k)
print(k.dtype)
print(k.shape)

[ 5  6 11 10 32]
int32
(5,)


# create array with single high multipal low

In [46]:
l =np.random.randint([10,20,30,40],50)
print(l)
print(l.dtype)
print(l.shape)


[11 37 42 46]
int32
(4,)


# create array with multipal low mulyipal high

In [55]:
m =np.random.randint([1,2,3],[10,20,30])
print(m)
print(m.dtype)
print(m.shape)

[ 8  2 20]
int32
(3,)


# random.randn function 1D

In [6]:
n = np.random.randn(3)
n

array([ 1.94243754, -0.10353373, -0.4364964 ])

# random.randn function 2D

In [8]:
o =np.random.randn(3,3)
print(o)
print(o.dtype)
print(o.shape)
print(o.size)

[[-1.73520976 -2.0023831  -0.16295334]
 [-0.51760461 -0.53569093 -1.15980776]
 [ 0.96026035  0.64355391 -0.81169397]]
float64
(3, 3)
9


# random.randn function 3D

In [9]:
p =np.random.randn(3,3,3)
print(p)
print(p.dtype)
print(p.shape)
print(p.size)

[[[-0.21156386  0.0418125   0.10536525]
  [-0.08084253 -0.48485738  1.83621259]
  [ 0.92599753  1.37473509  0.49033596]]

 [[ 1.0931343   0.48353196 -0.15048201]
  [-1.60066648  1.96954599  0.61689555]
  [-0.64111122 -0.14246892  0.17750181]]

 [[-0.46066347 -1.27994524 -1.28526682]
  [-0.04252425 -1.71685747  0.62458533]
  [-0.72819043 -1.76834001  1.49397406]]]
float64
(3, 3, 3)
27


# creating rand function

In [6]:
q =np.random.rand(10)
print(q)
print(q.shape)
print(q.dtype)
print(q.size)

[0.41146508 0.22117568 0.60768881 0.33097466 0.04932252 0.5822742
 0.0908129  0.63495455 0.60905582 0.18013633]
(10,)
float64
10


# creating array positive indexing

In [12]:
r =np.array([1,2,3,4])
print(r[3])

4


# creating array positive indexing 2D

In [15]:
r =np.array([[1,2,3,4],[5,6,7,8]])
print(r[1,0])
print(r[0,2])

5
3


# creating array positive indexing 3D

In [18]:
r =np.array(
    [
        [[1,2,3],[2,3,4]],
        [[3,4,5],[4,5,6]],
        [[5,6,7],[6,7,8]]
    ]
)
print(r[0,1,0])
print(r[1,1,2])

2
6


# creating array negative indexing 1D

In [19]:
s =np.array([1,2,3,4,5])
print(s[-2])

4


# creating array negative indexing 2D

In [21]:
s =np.array([[1,2,3,4],[5,6,7,8]])
print(s[-1,-1])
print(s[-2,-3])

8
2


# creating array negative indexing 3D

In [30]:
s =np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
print(s[-1,-1,-3])
print(s[-1,-2,-1])
print(s[-3,-1,-1])

6
7
4


# numpy array slicing

# slice elements from index 1to index 5 from the folling array

In [6]:
        #    0 1 2 3 4 5   
t =np.array([1,2,3,4,5,6])
print(t[1:5])

[2 3 4 5]


# slice elements from index 4to end array


In [7]:
        #    0 1 2 3 4 5 6
t =np.array([1,2,3,4,5,6,7])
print(t[4:7])

[5 6 7]


# slice elements from start to index 4 (not include)

In [8]:
#            0 1 2 3 4
t =np.array([1,2,3,4,5])
print(t[:4])

[1 2 3 4]


# negative slicing

slice from index 3 from end of to index 1 from end


In [10]:
 #           7 6 5 4 3 2 1
u =np.array([1,2,3,4,5,6,7])
print(u[-3:-1])

[5 6]


return every eliments from index 1 to index 5

In [13]:
u =np.array([1,2,3,4,5,6,7])
print(u[-1:-5:-2])

[7 5]


return every outher elements from the entire array

In [14]:
u =np.array([1,2,3,4,5,6,7])
print(u[::3])

[1 4 7]


# slicing 2d array

from second element from index 1 to index 4 (not included)

In [16]:
v =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(v[1,1:4])
print(v[0,0:4])

[7 8 9]
[1 2 3 4]


# from both array return index 2

In [17]:
v =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(v[0:2,1:4])

[[2 3 4]
 [7 8 9]]
